steps:
  # 0. ASEGURAR QUE EL REPOSITORIO EXISTA
  # Si el repositorio ms-motor-responsabilidad no existe, lo crea automáticamente.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud artifacts repositories create ms-motor-responsabilidad \
        --repository-format=docker \
        --location=us-east1 \
        --description="Repositorio para el Motor de Responsabilidad" || exit 0

  # 1. CONSTRUCCIÓN DE LA IMAGEN (BUILD)
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-east1-docker.pkg.dev/$PROJECT_ID/ms-motor-responsabilidad/motor-img:$COMMIT_SHA',
      '.'
    ]

  # 2. SUBIDA AL REGISTRO (PUSH)
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-east1-docker.pkg.dev/$PROJECT_ID/ms-motor-responsabilidad/motor-img:$COMMIT_SHA'
    ]

  # 3. DESPLIEGUE A CLOUD RUN (Configuración de Alta Potencia y Pública)
  - id: "deploy-cloud-run"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        gcloud run deploy ia-mv-motor-responsabilidad \
        --region us-east1 \
        --image us-east1-docker.pkg.dev/$PROJECT_ID/ms-motor-responsabilidad/motor-img:$COMMIT_SHA \
        --allow-unauthenticated \
        --port 8080 \
        --memory 8Gi \
        --cpu 4 \
        --timeout 600 \
        --concurrency 80 \
        --cpu-boost \
        --no-cpu-throttling \
        --use-http2 \
        --set-env-vars PROJECT_ID=$PROJECT_ID,GCS_BUCKET_NAME=bucket-motor-responsabilidad,APP_ENV=sbx \
        --labels billing-tag=ia-mv-motor-responsabilidad,vp=patrimoniales,team=movildiad,tipo=proyecto

# ✅ CORRECCIÓN DEL ERROR DE LOGS Y SERVICE ACCOUNT
options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'us-east1-docker.pkg.dev/$PROJECT_ID/ms-motor-responsabilidad/motor-img:$COMMIT_SHA'